### ISSUE TITLE
[docs][chore] add documentation for the api surface

### ISSUE THREAD

**Issue by BeauBouchard** [Crucible-Standard/meteorology#285]
The API should be a learning utility and well documented.

[Programableweb](https://en.wikipedia.org/wiki/ProgrammableWeb) no longer exists as of Feb 2023, We previously had a lot of exposure from their listing as a learning resource, and would like to document the free api on other platforms. [rapidapi](https://rapidapi.com) is a robust platform which has a lot of good free resources for small teams, it also gets people started using the api with code snippets and allows for people to query the api in a `postman` like web panel. 

### Tasks
* [x] Create a swagger/oapi3.0 document for the API
* [x] Create organization on `rapidapi`
* [x] Create fortunecookie documentation as apart of the org
* [x] update `README.md` with new link to the rapidapi page

**Comment by BeauBouchard** [comment]
work completed in https://github.com/Crucible-Standard/meteorology/pull/288
